---
- hosts: localhost
  gather_facts: yes

  pre_tasks:
      - name: Install Desktop
        package:
            name: "{{ item }}"
            state: present
        items:
            - "xubuntu-core"
            - "firefox"
            - "chromium-browser"
            - "evince"
        become: yes

  roles:
      - kurron.logfaces
      - kurron.atlassian
      - kurron.aws
      - kurron.docker-host
      - { role: kurron.hashicorp, hashicorp_vagrant_install: false }
      - kurron.javascript-developer
      - kurron.jvm-developer
      - { role: kurron.operations, operations_loggly_install: false, operations_datadog_install: false }
      - kurron.python-developer
      - kurron.software-developer
      - kurron.sql-developer

  post_tasks:
      - name: Determine VirtualBox Version
        command: "cat {{ansible_user_dir}}/.vbox_version"
        register: vbox_version
      - name: Soft-link Guest Additions ISO
        command: "ln -s {{ansible_user_dir}}/VBoxGuestAdditions_{{ vbox_version.stdout }}.iso /tmp/VBoxGuestAdditions_{{ vbox_version.stdout }}.iso"
      - name: Mount Guest Additions
        command: "mount -o loop /tmp/VBoxGuestAdditions_{{ vbox_version.stdout }}.iso /mnt"
        become: yes
      - name: Install Guest Additions
        command: "/mnt/VBoxLinuxAdditions.run"
        become: yes
      - name: Unmount Guest Additions
        command: "umount /mnt"
        become: yes
      - name: Clear out Downloads
        shell: "rm -f {{ansible_user_dir}}/Downloads/*.*"
      - name: Clear Out Guest Additions
        shell: "rm -f {{ansible_user_dir}}/*.iso"
      - name: Erase downloaded archive files
        shell: "apt-get -y clean"
        become: yes
